import {calculateNutrition,recipeNutrition,rankRecipes,parsePantryQuantity,parseIngredientNames,pantryInventory,resolveIngredient,recipeMatch,searchPantry} from './core.mjs';
import {recognizeFood} from './recognition-client.mjs';
import {estimateDish,dishCatalog} from './estimation.mjs';
import {assessPredictions} from './food-vocabulary.mjs';
import {localDate,mealDate,dailyNutrition,makeMeal,mergeGroceries,recipeShortages,variedRecommendations,MEAL_CATEGORIES} from './kitchen.mjs';
import {openKitchen,records,write,replaceRecords} from './storage.mjs';
const $=id=>document.getElementById(id), esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(v,d=1)=>v==null?'—':Number(v).toFixed(d), uid=()=>crypto.randomUUID(), gram=v=>Number(v.toFixed(1)).toLocaleString();
let foods,recipes,pantry=[],favorites=[],meals=[],portions=[],photo=null,result=null,editPantry=null,currentMatches=[],screen='scanner';
let installPrompt=null;window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;$('install-button').hidden=false;});window.addEventListener('appinstalled',()=>{$('install-button').hidden=true;installPrompt=null;});
let toastTimer,analysisRun=0,lastPrediction=null,groceries=[],editingMeal=null;
const sessionPredictions=new Map();let currentStock=null;
const paths={scan:'M4 8V5a1 1 0 0 1 1-1h3m8 0h3a1 1 0 0 1 1 1v3m0 8v3a1 1 0 0 1-1 1h-3m-8 0H5a1 1 0 0 1-1-1v-3M8 12h8',pantry:'M4 5h16v16H4zM3 2h18v3H3zM9 9h6m-6 5h6',heart:'M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z',camera:'M5 7h3l2-3h4l2 3h3a2 2 0 0 1 2 2v10H3V9a2 2 0 0 1 2-2Zm7 3a3 3 0 1 0 0 6 3 3 0 0 0 0-6Z',upload:'M12 16V3m-5 5 5-5 5 5M4 15v5h16v-5',chart:'M4 20V10m8 10V4m8 16V13',info:'M12 8v1m0 3v5M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20Z',bookmark:'M6 3h12v18l-6-4-6 4V3Z'};
const icon=name=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.info}"/></svg>`;
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,5500);}
function guard(action){return async event=>{try{await action(event);}catch(e){toast(e.message||'Something went wrong. Please try again.');}};}
function resolveFood(name){return resolveIngredient(name,foods);}
function showScreen(target){screen=['scanner','pantry','kitchen'].includes(target)?target:'scanner';document.querySelectorAll('.screen').forEach(s=>s.hidden=s.id!==screen);document.querySelectorAll('[data-screen]').forEach(b=>{b.classList.toggle('active',b.dataset.screen===screen);b.setAttribute('aria-current',b.dataset.screen===screen?'page':'false');});if(screen==='kitchen')renderKitchen();history.replaceState(null,'',`#${screen}`);window.scrollTo({top:0,behavior:'instant'});}
function invalidate(){result=null;$('save-meal').disabled=true;renderNutrition();$('breakdown').hidden=true;}
function addPortion(food='',grams=''){portions.push({id:uid(),food,name:foods.get(food)?.name||'',grams,source:'user'});renderPortions();invalidate();}
function renderPortions(){
 $('ingredient-rows').innerHTML=portions.map(p=>`<div class="ingredient-row" data-id="${p.id}"><div><input aria-label="Ingredient name" list="foods" value="${esc(p.name)}" placeholder="Choose ingredient…" autocomplete="off"><small data-estimate-origin>${p.source==='template'?'Recipe assumption · approximate grams':'User supplied / confirmed'}</small><p class="row-hint" ${p.name&&!foods.has(p.food)?'':'hidden'}>Choose a supported ingredient.</p></div><div class="qty-wrapper"><input aria-label="Quantity in grams" type="number" min="0.01" max="100000" step="any" value="${esc(p.grams)}" placeholder="0"><span>g</span></div><button class="delete-ingredient" aria-label="Remove ingredient">×</button></div>`).join('');
 $('ingredient-rows').querySelectorAll('.ingredient-row').forEach(row=>{
  const p=portions.find(p=>p.id===row.dataset.id),inputs=row.querySelectorAll('input');
  inputs[0].oninput=()=>{p.source='user';row.querySelector('[data-estimate-origin]').textContent='User supplied / confirmed';p.name=inputs[0].value;p.food=resolveFood(p.name)?.id||'';row.querySelector('.row-hint').hidden=!p.name||!!p.food;invalidate();};
  inputs[1].oninput=()=>{p.source='user';row.querySelector('[data-estimate-origin]').textContent='User supplied / confirmed';p.grams=inputs[1].value;invalidate();};
  row.querySelector('button').onclick=()=>{portions=portions.filter(p=>p.id!==row.dataset.id);renderPortions();invalidate();};
 });
}
function renderNutrition(){const m=result?.total;$('nutrition-results').innerHTML=`<div class="energy-card"><span>TOTAL ENERGY</span><strong>${fmt(m?.kcal,0)}</strong><small>kilocalories · kcal</small></div><div class="macro-cards">${[['protein','Protein'],['carbs','Carbs'],['fat','Fat']].map(([key,name])=>`<div class="macro-card"><span>${name}</span><strong>${fmt(m?.[key])}<small>g</small></strong></div>`).join('')}</div>`;
 if(!m){$('macro-chart').innerHTML='<p class="chart-caption">Your confirmed ingredients make the difference.</p>';return;}
 const energy=[m.protein*4,m.carbs*4,m.fat*9],sum=energy.reduce((a,b)=>a+b,0),colors=['#89a977','#c3ce9d','#d8b888'];
 $('macro-chart').innerHTML=`<div class="macro-bar" role="img" aria-label="Relative energy from protein, carbohydrates, and fat using 4/4/9 factors">${energy.map((v,i)=>`<span style="width:${sum?v/sum*100:0}%;background:${colors[i]}"></span>`).join('')}</div><div class="macro-legend">${['Protein','Carbs','Fat'].map((v,i)=>`<span><i style="background:${colors[i]}"></i>${v}</span>`).join('')}</div><p class="chart-caption">Relative macro energy · 4 / 4 / 9 approximation</p>`;
}
async function readPhoto(file){
 if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Choose a JPEG, PNG, or WebP image.');
 if(file.size>10*1024*1024)throw new Error('This photo is too large. Choose an image under 10 MB.');
 const url=URL.createObjectURL(file),image=new Image();
 try{image.src=url;await image.decode();if(!image.naturalWidth||!image.naturalHeight||image.naturalWidth*image.naturalHeight>50000000)throw new Error('Choose an image smaller than 50 megapixels.');
  const canvas=document.createElement('canvas'),scale=Math.min(1,1200/Math.max(image.naturalWidth,image.naturalHeight));canvas.width=Math.round(image.naturalWidth*scale);canvas.height=Math.round(image.naturalHeight*scale);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);photo=canvas.toDataURL('image/jpeg',.82);
 }catch(e){if(e.message?.includes('50 megapixels'))throw e;throw new Error('This file could not be decoded as a photo. Please choose another image.');}finally{URL.revokeObjectURL(url);}
 renderPhoto();await analyzePhoto();
}
function renderPhoto(){if(photo){$('photo-preview').innerHTML=`<img src="${photo}" alt="Your selected meal photo">`;}else{$('photo-preview').innerHTML=`<div class="photo-placeholder"><span>${icon('camera')}</span><h3>Start with a photo</h3><p>Snap your plate or choose a photo.<br>Nothing is uploaded to a server.</p></div>`;}$('clear-photo').hidden=!photo;}
function applyEstimate(label,score=null,provisional=false){
 const estimate=estimateDish(label,Number($('portion-scale').value));
 portions=estimate.ingredients.map(p=>({...p,id:uid(),name:foods.get(p.food).name}));
 $('meal-name').value=estimate.name;renderPortions();$('calculate-button').click();
 $('analysis-status').textContent=`Probable dish: ${estimate.name}${score==null?'':` · model score ${Math.round(score*100)}% (not a calibrated confidence)`}. ${provisional?'Provisional match: visually similar dishes scored closely; compare the alternatives below. ':''}${estimate.visualEvidence} Estimated nutrition based on probable ingredients and approximate serving size. Actual values may vary. All listed ingredients are typical recipe assumptions. Assumes ${estimate.scale} standard serving(s), not measured from the photo. ${estimate.note} Hidden oils, sauces and mixed-meal components may be missed. Edit anything below to recalculate.`;
 $('dish-correction').value=estimate.name;
 $('analysis-status').hidden=false;
}
async function analyzePhoto(){
 if(!photo){toast('Choose a food photo first.');return;}
 const run=++analysisRun,snapshot=photo;lastPrediction=null;portions=[];renderPortions();invalidate();$('predictions').innerHTML='';$('dish-correction').value='';$('meal-name').value='';
 $('analyze-button').disabled=true;$('analysis-status').hidden=false;
 try{
  const predictions=sessionPredictions.get(snapshot)||await recognizeFood(snapshot,message=>{if(run===analysisRun)$('analysis-status').textContent=message;});
  sessionPredictions.set(snapshot,predictions);
  if(run!==analysisRun)return;
  const decision=assessPredictions(predictions);renderPredictions(decision.predictions);
  if(decision.status==='selected'){lastPrediction={...decision.best,provisional:!!decision.provisional};applyEstimate(decision.best.label,decision.best.score,decision.provisional);}
  else{$('analysis-status').textContent=decision.message;$('dish-correction-details').open=true;}
 }catch(error){if(run===analysisRun){$('analysis-status').textContent=error.message;toast(error.message);}}
 finally{if(run===analysisRun)$('analyze-button').disabled=false;}
}
function renderPredictions(predictions){$('predictions').innerHTML='<p class="input-hint">Top plausible matches · relative model scores, not measured certainty</p>'+predictions.map(p=>`<button class="prediction secondary" data-prediction="${esc(p.label)}" ${p.kind==='nonfood'?'disabled':''}>${esc(p.name)} <small>${fmt(p.score*100,0)}%</small></button>`).join('');$('predictions').querySelectorAll('[data-prediction]').forEach(b=>b.onclick=guard(async()=>{const p=predictions.find(p=>p.label===b.dataset.prediction);lastPrediction=p;applyEstimate(p.label,p.score);}));}
async function refreshKitchen(){[pantry,favorites,meals,groceries]=await Promise.all([records('pantry'),records('favorites'),records('meals'),records('groceries')]);pantry.sort((a,b)=>(foods.get(a.food)?.name||a.food).localeCompare(foods.get(b.food)?.name||b.food));meals.sort((a,b)=>b.createdAt.localeCompare(a.createdAt));renderPantry();if(screen==='kitchen')renderKitchen();}
function pantryMarkup(items,editable=true){return items.map(p=>`<div class="pantry-item"><div><strong>${esc(foods.get(p.food)?.name||p.food)}</strong><small>${p.grams==null?'Available · quantity not specified':gram(p.grams)+' g'}${p.unit==='pieces'?` · ${p.quantity} eggs, approximate`:''}</small></div>${editable?`<div class="item-actions"><button data-edit="${p.id}" aria-label="Edit ${esc(foods.get(p.food)?.name||p.food)}">Edit</button><button data-delete="${p.id}" aria-label="Delete ${esc(foods.get(p.food)?.name||p.food)}">Delete</button></div>`:''}</div>`).join('');}
function empty(title,text){return `<div class="empty-state"><span>✧</span><h3>${esc(title)}</h3><p>${esc(text)}</p></div>`;}
function renderPantry(){$('pantry-count').textContent=`${pantry.length} ${pantry.length===1?'item':'items'}`;$('pantry-items').innerHTML=pantry.length?pantryMarkup(pantry):empty('A fresh start','Add an ingredient above to begin filling your pantry.');
 $('pantry-items').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const p=pantry.find(p=>p.id===b.dataset.edit);editPantry=p.id;$('pantry-food').value=foods.get(p.food).name;$('pantry-quantity').value=p.quantity??p.grams??'';$('pantry-unit').value=p.unit||'g';$('pantry-submit').textContent='Save changes';$('cancel-edit').hidden=false;$('pantry-food').focus();});
 $('pantry-items').querySelectorAll('[data-delete]').forEach(b=>b.onclick=guard(async()=>{await write('pantry',b.dataset.delete,true);await refreshKitchen();resetRecommendations();toast('Ingredient removed from your pantry.');}));
}
function resetPantryForm(){editPantry=null;$('pantry-form').reset();$('pantry-submit').textContent='＋ Add to pantry';$('cancel-edit').hidden=true;}
function resetRecommendations(){currentMatches=[];currentStock=null;$('recipe-results').innerHTML=empty('Something good is waiting','Add what you have, then tap “What can I cook?” to find matching meals.');}
const isFavorite=id=>favorites.some(f=>f.id===id);
function recipeCard(recipe,match=null){const m=match?.macros||recipeNutrition(recipe,foods);return `<article class="recipe-card"><div class="recipe-photo"><img src="images/${recipe.image}.jpg" alt="${esc(recipe.name)} serving suggestion" loading="lazy" width="1000" height="667"><span class="photo-label">Licensed serving suggestion · not AI generated</span><button class="heart-button ${isFavorite(recipe.id)?'saved':''}" data-favorite="${recipe.id}" aria-label="${isFavorite(recipe.id)?'Remove saved':'Save'} ${esc(recipe.name)}" aria-pressed="${isFavorite(recipe.id)}">${isFavorite(recipe.id)?'♥':'♡'}</button></div><div class="recipe-body"><div class="recipe-meta"><span>${recipe.minutes} MIN</span><span>${recipe.servings} ${recipe.servings===1?'SERVING':'SERVINGS'}</span>${recipe.tags.length?`<span>${recipe.tags.includes('vegan')?'VEGAN':'VEGETARIAN'}</span>`:''}</div><h3>${esc(recipe.name)}</h3><p>${esc(recipe.description)}</p>${match?`<div class="coverage-track"><span style="width:${match.coverage*100}%"></span></div><div class="coverage-note"><strong>${match.ready?'READY TO COOK':'ALMOST POSSIBLE'}</strong> · ${fmt(match.coverage*100,0)}% ${match.namesOnly?'ingredient match':'quantity coverage'} · ${match.missing.length?match.missing.length+' ingredient(s) missing':match.namesOnly?'Listed ingredients present; amounts assumed':'Everything available in your pantry'}</div>`:''}${match?`<p class="input-hint">${match.ready?'All essential ingredients available; amounts are standard assumptions.':'Obtain the listed missing essentials before cooking. Nutrition assumes the full essential recipe.'}${match.missingOptional.length?' Optional and omitted: '+match.missingOptional.map(p=>esc(foods.get(p.food).name)).join(', '):''}</p>`:''}<div class="recipe-macros"><span><b>${fmt(m.kcal,0)}</b> kcal</span><span><b>${fmt(m.protein)}</b> g protein</span><span><b>${fmt(m.carbs)}</b> g carbs</span><span><b>${fmt(m.fat)}</b> g fat</span></div><ol class="quick-steps">${recipe.steps.map(step=>`<li>${esc(step)}</li>`).join('')}</ol>${match?.missing.length?`<p class="input-hint">Missing: ${match.missing.map(p=>esc(foods.get(p.food).name)).join(', ')}</p><button class="secondary grocery-add" data-add-missing="${recipe.id}">Add missing ingredients</button>`:''}<div class="recipe-bottom"><span class="input-hint">Estimates per serving · standard recipe weights</span><button class="primary" data-recipe="${recipe.id}">View recipe ↗</button></div></div></article>`;}
function bindRecipes(container){bindPhotoFallback(container);container.querySelectorAll('[data-add-missing]').forEach(b=>b.onclick=guard(async()=>addMissing(b.dataset.addMissing,container===$('recipe-results')?currentStock:pantry)));container.querySelectorAll('[data-recipe]').forEach(b=>b.onclick=()=>showRecipe(b.dataset.recipe,container===$('recipe-results')?currentStock:pantry));container.querySelectorAll('[data-favorite]').forEach(b=>b.onclick=guard(async()=>{const id=b.dataset.favorite,save=!isFavorite(id);await write('favorites',save?{id}:id,!save);await refreshKitchen();renderMatches();toast(save?'Recipe saved to your kitchen.':'Recipe removed from saved recipes.');}));}
function renderMatches(){
 const ready=currentMatches.filter(m=>m.ready),almost=currentMatches.filter(m=>!m.ready);
 $('recipe-results').innerHTML=currentMatches.length?`<p class="input-hint">Matching only: ${(currentStock||pantry).map(p=>esc(foods.get(p.food).name)).join(', ')}. No other pantry stock or substantial staples are assumed.</p><h2>Ready to cook</h2>${ready.length?ready.map(m=>recipeCard(m.recipe,m)).join(''):empty('No fully achievable recipe yet','The ideas below require missing essential ingredients.')} ${almost.length?'<h2>Almost possible — missing essentials</h2>'+almost.map(m=>recipeCard(m.recipe,m)).join(''):''}`:empty('No suitable recipes',pantry.length||currentStock?.length?'No ready or closely matching recipe meets this ingredient list and calorie range. Add ingredients or widen the range.':'Add ingredient names to begin. An empty pantry produces no suggestions.');bindRecipes($('recipe-results'));
}

function bindPhotoFallback(container){container.querySelectorAll('img').forEach(img=>{img.onerror=()=>{img.onerror=null;img.src='images/food-fallback.svg';img.alt='Food illustration: photograph unavailable';};});}
async function addMissing(id,stock=pantry){const recipe=recipes.find(r=>r.id===id);groceries=mergeGroceries(groceries,recipe,stock,foods);await replaceRecords('groceries',groceries);if(screen==='kitchen')renderGroceries();toast('Missing ingredients saved to your grocery checklist in My kitchen.');}
function showRecipe(id,stock=pantry){const r=recipes.find(r=>r.id===id),match=recipeMatch(r,stock,foods),m=match.macros,inventory=pantryInventory(stock,foods);
 $('recipe-dialog-content').innerHTML=`<img src="images/${r.image}.jpg" alt="Licensed serving suggestion"><p class="eyebrow">${r.minutes} MINUTES · ${r.servings} ${r.servings===1?'SERVING':'SERVINGS'}</p><h2>${esc(r.name)}</h2><p>${esc(r.description)}</p><p class="input-hint">Bundled food photograph; a serving suggestion, not a newly generated AI image.</p><div class="recipe-modal-macros">Per serving: ${fmt(m.kcal,0)} kcal · ${fmt(m.protein)} g protein · ${fmt(m.carbs)} g carbs · ${fmt(m.fat)} g fat</div><h3>Ingredients for the whole recipe</h3>${r.ingredients.map(p=>{const need=Math.max(0,p.grams-(inventory.get(p.food)||0)),optional=r.optionalIngredients.includes(p.food);return `<div class="dialog-ingredient"><span>${esc(foods.get(p.food).name)}<small class="missing-badge">${need?` · ${optional?'Optional, omitted from nutrition':'Essential: need '+gram(need)+' g more'}`:inventory.get(p.food)===Infinity?' · Listed in pantry; quantity assumed':' · Available'}</small></span><b>${gram(p.grams)} g</b></div>`;}).join('')}${recipeShortages(r,stock,foods).length?'<button class="secondary" id="dialog-add-missing">Add missing ingredients</button>':''}<h3>Make it, step by step</h3><ol>${r.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><p class="input-hint">Nutrition uses the listed ingredient weights and raw/cooked forms. Absent optional ingredients are not included; available listed optionals are counted. Check packaging and your own needs before relying on dietary labels.</p><div class="dialog-actions"><button class="primary" id="use-recipe">Log my version</button><button class="secondary" id="dialog-save-recipe">${isFavorite(id)?'Remove from saved':'Save recipe'}</button></div>`;
 $('use-recipe').onclick=()=>{$('recipe-dialog').close();useTemplate(r.id,stock);showScreen('scanner');toast('Ingredients added as a starting point. Confirm your own quantities.');};
 $('dialog-save-recipe').onclick=guard(async()=>{const save=!isFavorite(id);await write('favorites',save?{id}:id,!save);await refreshKitchen();renderMatches();$('dialog-save-recipe').textContent=save?'Remove from saved':'Save recipe';toast(save?'Recipe saved.':'Recipe removed.');});
 bindPhotoFallback($('recipe-dialog-content'));if($('dialog-add-missing'))$('dialog-add-missing').onclick=guard(async()=>addMissing(id,stock));
 $('recipe-dialog').showModal();
}
function useTemplate(id,stock=pantry){const r=recipes.find(r=>r.id===id);if(!r)return;portions=recipeMatch(r,stock,foods).ingredients.map(p=>({id:uid(),food:p.food,name:foods.get(p.food).name,grams:p.grams/r.servings,source:'template'}));editingMeal=null;$('cancel-meal-edit').hidden=true;$('save-meal').textContent='Save to food diary';$('meal-name').value=r.name;$('template').value=id;renderPortions();$('calculate-button').click();}
function renderKitchen(){$('kitchen-stats').innerHTML=[['Pantry ingredients',pantry.length],['Saved recipes',favorites.length],['Meals remembered',meals.length]].map(([title,value])=>`<div class="kitchen-stat"><strong>${value}</strong><span>${title}</span></div>`).join('');const saved=recipes.filter(r=>isFavorite(r.id));$('favorite-recipes').innerHTML=saved.length?saved.map(r=>recipeCard(r)).join(''):empty('Keep your favorites close','Save a recipe from your pantry recommendations to see it here.');bindRecipes($('favorite-recipes'));
 renderDiary();renderGroceries();$('kitchen-pantry').innerHTML=pantry.length?pantryMarkup(pantry,false):empty('Your pantry is empty','Add ingredients in “Cook from my pantry” to get started.');}
function renderDiary(){
 const date=$('diary-date').value||localDate(),daily=dailyNutrition(meals,date),m=daily.total;
 $('diary-totals').innerHTML=[['kcal','Calories','kcal'],['protein','Protein','g'],['carbs','Carbs','g'],['fat','Fat','g']].map(([key,title,unit])=>`<div class="kitchen-stat"><strong>${fmt(m[key],key==='kcal'?0:1)}<small> ${unit}</small></strong><span>${title}</span></div>`).join('');
 const ordered=[...meals].sort((a,b)=>mealDate(b).localeCompare(mealDate(a))||b.createdAt.localeCompare(a.createdAt));
 $('meal-history').innerHTML=ordered.length?ordered.map(m=>`<article class="meal-log ${mealDate(m)===date?'selected-day':''}">${m.photo?`<img class="meal-thumb" src="${m.photo}" alt="Your saved meal photo">`:'<div class="meal-thumb">♧</div>'}<div><h3>${esc(m.name)}</h3><p>${esc(mealDate(m))} · ${esc(m.category||'snacks')} · ${m.portions.length} ingredients</p><div class="log-macros">${fmt(m.total.kcal,0)} kcal · ${fmt(m.total.protein)} g protein · ${fmt(m.total.carbs)} g carbs · ${fmt(m.total.fat)} g fat</div></div><div class="item-actions"><button data-edit-meal="${m.id}">Edit</button><button data-delete-meal="${m.id}" aria-label="Delete ${esc(m.name)}">Delete</button></div></article>`).join(''):empty('Remember a good meal','Save a scanned or manually calculated meal to start your diary.');
 $('meal-history').querySelectorAll('[data-edit-meal]').forEach(b=>b.onclick=()=>{const m=meals.find(m=>m.id===b.dataset.editMeal);++analysisRun;editingMeal=m;photo=m.photo;lastPrediction=null;portions=m.portions.map(p=>({...p,id:uid(),name:foods.get(p.food)?.name||p.food}));$('meal-name').value=m.name;$('meal-date').value=mealDate(m);$('meal-category').value=m.category||'snacks';$('save-meal').textContent='Save diary changes';$('cancel-meal-edit').hidden=false;$('analysis-status').hidden=true;$('predictions').innerHTML='';$('analyze-button').disabled=false;renderPhoto();renderPortions();$('calculate-button').click();showScreen('scanner');toast('Editing your saved meal. Update ingredients, date or category, then save.');});
 $('meal-history').querySelectorAll('[data-delete-meal]').forEach(b=>b.onclick=guard(async()=>{await write('meals',b.dataset.deleteMeal,true);if(editingMeal?.id===b.dataset.deleteMeal)cancelMealEdit();await refreshKitchen();toast('Meal removed from your diary.');}));
}
function cancelMealEdit(){editingMeal=null;$('save-meal').textContent='Save to food diary';$('cancel-meal-edit').hidden=true;}
function renderGroceries(){
 groceries.sort((a,b)=>Number(a.checked)-Number(b.checked)||foods.get(a.food).name.localeCompare(foods.get(b.food).name));
 $('grocery-count').textContent=`${groceries.filter(g=>!g.checked).length} to buy`;
 $('grocery-items').innerHTML=groceries.length?groceries.map(g=>`<div class="grocery-item"><label><input type="checkbox" data-grocery="${g.id}" ${g.checked?'checked':''}><span class="${g.checked?'checked':''}"><strong>${esc(foods.get(g.food).name)}</strong><small>${gram(g.grams)} g · ${Object.keys(g.sources).length} recipe(s), assumed amounts</small></span></label><button class="text-button" data-delete-grocery="${g.id}" aria-label="Remove ${esc(foods.get(g.food).name)} from groceries">Remove</button></div>`).join(''):empty('Your next shopping trip','Add missing ingredients from a recipe to build this checklist.');
 $('grocery-items').querySelectorAll('[data-grocery]').forEach(b=>b.onchange=guard(async()=>{const item=groceries.find(g=>g.id===b.dataset.grocery);await write('groceries',{...item,checked:b.checked});await refreshKitchen();}));
 $('grocery-items').querySelectorAll('[data-delete-grocery]').forEach(b=>b.onclick=guard(async()=>{await write('groceries',b.dataset.deleteGrocery,true);await refreshKitchen();}));
}

async function start(){
 try{
  const responses=await Promise.all([fetch('data/nutrition.json'),fetch('data/recipes.json')]);if(responses.some(r=>!r.ok))throw new Error('The food catalog could not load. Connect once and reload to set up offline use.');
  const [nutrition,recipeData]=await Promise.all(responses.map(r=>r.json()));foods=new Map(nutrition.ingredients.map(f=>[f.id,f]));recipes=recipeData;
  for(const r of recipes)recipeNutrition(r,foods);$('meal-date').value=localDate();$('diary-date').value=localDate();$('diary-date').onchange=guard(async()=>renderDiary());$('cancel-meal-edit').onclick=cancelMealEdit;$('dishes').innerHTML=dishCatalog().map(d=>`<option value="${esc(d.name)}"></option>`).join('');await openKitchen();await refreshKitchen();
  $('foods').innerHTML=[...foods.values()].sort((a,b)=>a.name.localeCompare(b.name)).map(f=>`<option value="${esc(f.name)}"></option>`).join('');$('template').innerHTML+=[...recipes].sort((a,b)=>a.name.localeCompare(b.name)).map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join('');
  document.querySelectorAll('[data-screen]').forEach(b=>b.onclick=()=>showScreen(b.dataset.screen));document.querySelectorAll('[data-go-pantry]').forEach(b=>b.onclick=()=>showScreen('pantry'));
  $('add-ingredient').onclick=()=>addPortion();$('template').onchange=()=>useTemplate($('template').value);
  $('camera-button').onclick=()=>$('camera-input').click();$('upload-button').onclick=()=>$('photo-input').click();
  for(const id of ['camera-input','photo-input'])$(id).onchange=guard(async()=>{await readPhoto($(id).files[0]);$(id).value='';});
  $('clear-photo').onclick=()=>{++analysisRun;lastPrediction=null;photo=null;portions=[];renderPortions();$('predictions').innerHTML='';renderPhoto();invalidate();$('analysis-status').hidden=true;$('analyze-button').disabled=false;};
  $('analyze-button').onclick=analyzePhoto;
  $('portion-scale').onchange=guard(async()=>{if(lastPrediction)applyEstimate(lastPrediction.label,lastPrediction.score,lastPrediction.provisional);});
  $('correct-dish').onclick=guard(async()=>{const label=$('dish-correction').value.trim();++analysisRun;$('analyze-button').disabled=false;applyEstimate(label);lastPrediction={label};});
  $('calculate-button').onclick=()=>{try{result=calculateNutrition(portions,foods);$('calculation-error').hidden=true;renderNutrition();$('save-meal').disabled=false;$('breakdown').hidden=false;$('breakdown-content').innerHTML=result.breakdown.map(p=>`<div class="breakdown-row"><span>${esc(p.name)} · ${gram(p.grams)} g</span><b>${fmt(p.kcal,0)} kcal</b></div>`).join('');toast('Calculated locally from the listed ingredient quantities.');}catch(e){invalidate();$('calculation-error').textContent=e.message;$('calculation-error').hidden=false;}};
  $('save-meal').onclick=guard(async()=>{if(!result)throw new Error('Calculate nutrition before saving.');const name=$('meal-name').value.trim();if(!name)throw new Error('Give your meal a name before saving.');const meal=makeMeal({id:editingMeal?.id||uid(),name,date:$('meal-date').value,category:$('meal-category').value,createdAt:editingMeal?.createdAt,portions:result.breakdown,photo},foods);await write('meals',meal);cancelMealEdit();$('diary-date').value=meal.date;await refreshKitchen();toast('Meal saved privately in your food diary.');});
  const savePantry=async()=>{const f=resolveFood($('pantry-food').value);const text=$('pantry-food').value,hasQuantity=$('pantry-quantity').value!=='';let items;if(hasQuantity){if(!f)throw new Error('With an optional quantity, enter one supported ingredient.');const grams=parsePantryQuantity(f.id,$('pantry-quantity').value,$('pantry-unit').value);items=[{id:f.id,food:f.id,grams,unit:$('pantry-unit').value,quantity:Number($('pantry-quantity').value)}];}else items=parseIngredientNames(text,foods);if(editPantry&&items.length!==1)throw new Error('Edit one pantry item at a time.');for(const item of items)await write('pantry',item,false,editPantry);resetPantryForm();await refreshKitchen();resetRecommendations();toast('Pantry saved on this device.');};$('pantry-form').onsubmit=guard(async e=>{e.preventDefault();await savePantry();});$('cancel-edit').onclick=resetPantryForm;
  $('pantry-food').oninput=resetRecommendations;
  $('recommend-button').onclick=guard(async()=>{resetRecommendations();currentStock=searchPantry($('pantry-food').value,pantry,foods);const bound=id=>$(id).value===''?null:Number($(id).value);const matches=rankRecipes(recipes,currentStock,foods,{preference:$('diet').value,minKcal:bound('min-calories'),maxKcal:bound('max-calories'),limit:recipes.length,includeAlmost:true});currentMatches=[...variedRecommendations(matches.filter(m=>m.ready)),...variedRecommendations(matches.filter(m=>!m.ready))];renderMatches();if(!currentStock.length)toast('Add ingredient names first.');});
  $('install-button').onclick=guard(async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null;$('install-button').hidden=true;}});
  $('about-button').onclick=()=>$('about-dialog').showModal();document.querySelectorAll('.dialog-close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
  for(const dialog of document.querySelectorAll('dialog'))dialog.onclick=e=>{if(e.target===dialog){const rect=dialog.getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)dialog.close();}};
  addPortion();resetRecommendations();$('app-loading').hidden=true;showScreen(location.hash.slice(1));
  if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').then(()=>{navigator.serviceWorker.ready.then(()=>{$('offline-status').textContent=navigator.onLine?'Offline ready':'Offline mode';});}).catch(()=>{$('offline-status').textContent='Local & private';});
  window.addEventListener('online',()=>$('offline-status').textContent='Local & private');window.addEventListener('offline',()=>$('offline-status').textContent='Offline mode');
 }catch(e){$('app-loading').hidden=true;$('app-error').hidden=false;$('app-error').textContent=e.message;}
}
start();
