import {calculateNutrition,recipeNutrition,rankRecipes,parsePantryQuantity} from './core.mjs';
import {openKitchen,records,write} from './storage.mjs';
const $=id=>document.getElementById(id), esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(v,d=1)=>v==null?'—':Number(v).toFixed(d), uid=()=>crypto.randomUUID(), gram=v=>Number(v.toFixed(1)).toLocaleString();
let foods,recipes,pantry=[],favorites=[],meals=[],portions=[],photo=null,result=null,editPantry=null,currentMatches=[],screen='scanner';
let toastTimer;
const paths={scan:'M4 8V5a1 1 0 0 1 1-1h3m8 0h3a1 1 0 0 1 1 1v3m0 8v3a1 1 0 0 1-1 1h-3m-8 0H5a1 1 0 0 1-1-1v-3M8 12h8',pantry:'M4 5h16v16H4zM3 2h18v3H3zM9 9h6m-6 5h6',heart:'M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z',camera:'M5 7h3l2-3h4l2 3h3a2 2 0 0 1 2 2v10H3V9a2 2 0 0 1 2-2Zm7 3a3 3 0 1 0 0 6 3 3 0 0 0 0-6Z',upload:'M12 16V3m-5 5 5-5 5 5M4 15v5h16v-5',chart:'M4 20V10m8 10V4m8 16V13',info:'M12 8v1m0 3v5M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20Z',bookmark:'M6 3h12v18l-6-4-6 4V3Z'};
const icon=name=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.info}"/></svg>`;
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,5500);}
function guard(action){return async event=>{try{await action(event);}catch(e){toast(e.message||'Something went wrong. Please try again.');}};}
function resolveFood(name){return [...foods.values()].find(f=>f.name.toLowerCase()===name.trim().toLowerCase());}
function showScreen(target){screen=['scanner','pantry','kitchen'].includes(target)?target:'scanner';document.querySelectorAll('.screen').forEach(s=>s.hidden=s.id!==screen);document.querySelectorAll('[data-screen]').forEach(b=>{b.classList.toggle('active',b.dataset.screen===screen);b.setAttribute('aria-current',b.dataset.screen===screen?'page':'false');});if(screen==='kitchen')renderKitchen();history.replaceState(null,'',`#${screen}`);window.scrollTo({top:0,behavior:'instant'});}
function invalidate(){result=null;$('save-meal').disabled=true;renderNutrition();$('breakdown').hidden=true;}
function addPortion(food='',grams=''){portions.push({id:uid(),food,name:foods.get(food)?.name||'',grams});renderPortions();invalidate();}
function renderPortions(){
 $('ingredient-rows').innerHTML=portions.map(p=>`<div class="ingredient-row" data-id="${p.id}"><div><input aria-label="Ingredient name" list="foods" value="${esc(p.name)}" placeholder="Choose ingredient…" autocomplete="off"><p class="row-hint" ${p.name&&!foods.has(p.food)?'':'hidden'}>Choose a supported ingredient.</p></div><div class="qty-wrapper"><input aria-label="Quantity in grams" type="number" min="0.01" max="100000" step="any" value="${esc(p.grams)}" placeholder="0"><span>g</span></div><button class="delete-ingredient" aria-label="Remove ingredient">×</button></div>`).join('');
 $('ingredient-rows').querySelectorAll('.ingredient-row').forEach(row=>{
  const p=portions.find(p=>p.id===row.dataset.id),inputs=row.querySelectorAll('input');
  inputs[0].oninput=()=>{p.name=inputs[0].value;p.food=resolveFood(p.name)?.id||'';row.querySelector('.row-hint').hidden=!p.name||!!p.food;invalidate();};
  inputs[1].oninput=()=>{p.grams=inputs[1].value;invalidate();};
  row.querySelector('button').onclick=()=>{portions=portions.filter(p=>p.id!==row.dataset.id);renderPortions();invalidate();};
 });
}
function renderNutrition(){const m=result?.total;$('nutrition-results').innerHTML=`<div class="energy-card"><span>TOTAL ENERGY</span><strong>${fmt(m?.kcal,0)}</strong><small>kilocalories · kcal</small></div><div class="macro-cards">${[['protein','Protein'],['carbs','Carbs'],['fat','Fat']].map(([key,name])=>`<div class="macro-card"><span>${name}</span><strong>${fmt(m?.[key])}<small>g</small></strong></div>`).join('')}</div>`;
 if(!m){$('macro-chart').innerHTML='<p class="chart-caption">Your confirmed ingredients make the difference.</p>';return;}
 const energy=[m.protein*4,m.carbs*4,m.fat*9],sum=energy.reduce((a,b)=>a+b,0),colors=['#89a977','#c3ce9d','#d8b888'];
 $('macro-chart').innerHTML=`<div class="macro-bar" role="img" aria-label="Relative energy from protein, carbohydrates, and fat using 4/4/9 factors">${energy.map((v,i)=>`<span style="width:${sum?v/sum*100:0}%;background:${colors[i]}"></span>`).join('')}</div><div class="macro-legend">${['Protein','Carbs','Fat'].map((v,i)=>`<span><i style="background:${colors[i]}"></i>${v}</span>`).join('')}</div><p class="chart-caption">Relative macro energy · 4 / 4 / 9 approximation</p>`;
}
async function readPhoto(file){
 if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Choose a JPEG, PNG, or WebP image.');
 if(file.size>10*1024*1024)throw new Error('This photo is too large. Choose an image under 10 MB.');
 const url=URL.createObjectURL(file),image=new Image();
 try{image.src=url;await image.decode();if(!image.naturalWidth||!image.naturalHeight||image.naturalWidth*image.naturalHeight>50000000)throw new Error('Choose an image smaller than 50 megapixels.');
  const canvas=document.createElement('canvas'),scale=Math.min(1,1200/Math.max(image.naturalWidth,image.naturalHeight));canvas.width=Math.round(image.naturalWidth*scale);canvas.height=Math.round(image.naturalHeight*scale);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);photo=canvas.toDataURL('image/jpeg',.82);
 }catch(e){if(e.message?.includes('50 megapixels'))throw e;throw new Error('This file could not be decoded as a photo. Please choose another image.');}finally{URL.revokeObjectURL(url);}
 renderPhoto();toast('Photo added locally. Confirm the ingredients and weights below.');
}
function renderPhoto(){if(photo){$('photo-preview').innerHTML=`<img src="${photo}" alt="Your selected meal photo">`;}else{$('photo-preview').innerHTML=`<div class="photo-placeholder"><span>${icon('camera')}</span><h3>Start with a photo</h3><p>Snap your plate or choose a photo.<br>Nothing is uploaded to a server.</p></div>`;}$('clear-photo').hidden=!photo;}
async function refreshKitchen(){[pantry,favorites,meals]=await Promise.all([records('pantry'),records('favorites'),records('meals')]);pantry.sort((a,b)=>(foods.get(a.food)?.name||a.food).localeCompare(foods.get(b.food)?.name||b.food));meals.sort((a,b)=>b.createdAt.localeCompare(a.createdAt));renderPantry();if(screen==='kitchen')renderKitchen();}
function pantryMarkup(items,editable=true){return items.map(p=>`<div class="pantry-item"><div><strong>${esc(foods.get(p.food)?.name||p.food)}</strong><small>${gram(p.grams)} g${p.unit==='pieces'?` · ${p.quantity} eggs, approximate`:''}</small></div>${editable?`<div class="item-actions"><button data-edit="${p.id}" aria-label="Edit ${esc(foods.get(p.food)?.name||p.food)}">Edit</button><button data-delete="${p.id}" aria-label="Delete ${esc(foods.get(p.food)?.name||p.food)}">Delete</button></div>`:''}</div>`).join('');}
function empty(title,text){return `<div class="empty-state"><span>✧</span><h3>${esc(title)}</h3><p>${esc(text)}</p></div>`;}
function renderPantry(){$('pantry-count').textContent=`${pantry.length} ${pantry.length===1?'item':'items'}`;$('pantry-items').innerHTML=pantry.length?pantryMarkup(pantry):empty('A fresh start','Add an ingredient above to begin filling your pantry.');
 $('pantry-items').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const p=pantry.find(p=>p.id===b.dataset.edit);editPantry=p.id;$('pantry-food').value=foods.get(p.food).name;$('pantry-quantity').value=p.quantity??p.grams;$('pantry-unit').value=p.unit||'g';$('pantry-submit').textContent='Save changes';$('cancel-edit').hidden=false;$('pantry-food').focus();});
 $('pantry-items').querySelectorAll('[data-delete]').forEach(b=>b.onclick=guard(async()=>{await write('pantry',b.dataset.delete,true);await refreshKitchen();resetRecommendations();toast('Ingredient removed from your pantry.');}));
}
function resetPantryForm(){editPantry=null;$('pantry-form').reset();$('pantry-submit').textContent='＋ Add to pantry';$('cancel-edit').hidden=true;}
function resetRecommendations(){currentMatches=[];$('recipe-results').innerHTML=empty('Something good is waiting','Add what you have, then tap “What can I cook?” to find matching meals.');}
const isFavorite=id=>favorites.some(f=>f.id===id);
function recipeCard(recipe,match=null){const m=match?.macros||recipeNutrition(recipe,foods);return `<article class="recipe-card"><div class="recipe-photo"><img src="images/${recipe.image}.jpg" alt="${esc(recipe.name)} serving suggestion" loading="lazy" width="1000" height="667"><span class="photo-label">Licensed serving suggestion · not AI generated</span><button class="heart-button ${isFavorite(recipe.id)?'saved':''}" data-favorite="${recipe.id}" aria-label="${isFavorite(recipe.id)?'Remove saved':'Save'} ${esc(recipe.name)}" aria-pressed="${isFavorite(recipe.id)}">${isFavorite(recipe.id)?'♥':'♡'}</button></div><div class="recipe-body"><div class="recipe-meta"><span>${recipe.minutes} MIN</span><span>${recipe.servings} ${recipe.servings===1?'SERVING':'SERVINGS'}</span>${recipe.tags.length?`<span>${recipe.tags.includes('vegan')?'VEGAN':'VEGETARIAN'}</span>`:''}</div><h3>${esc(recipe.name)}</h3><p>${esc(recipe.description)}</p>${match?`<div class="coverage-track"><span style="width:${match.coverage*100}%"></span></div><div class="coverage-note">${fmt(match.coverage*100,0)}% quantity coverage · ${match.missing.length?match.missing.length+' ingredient amounts missing':'Everything available in your pantry'}</div>`:''}<div class="recipe-macros"><span><b>${fmt(m.kcal,0)}</b> kcal</span><span><b>${fmt(m.protein)}</b> g protein</span><span><b>${fmt(m.carbs)}</b> g carbs</span><span><b>${fmt(m.fat)}</b> g fat</span></div><div class="recipe-bottom"><span class="input-hint">Estimates per serving</span><button class="primary" data-recipe="${recipe.id}">View recipe ↗</button></div></div></article>`;}
function bindRecipes(container){container.querySelectorAll('[data-recipe]').forEach(b=>b.onclick=()=>showRecipe(b.dataset.recipe));container.querySelectorAll('[data-favorite]').forEach(b=>b.onclick=guard(async()=>{const id=b.dataset.favorite,save=!isFavorite(id);await write('favorites',save?{id}:id,!save);await refreshKitchen();renderMatches();toast(save?'Recipe saved to your kitchen.':'Recipe removed from saved recipes.');}));}
function renderMatches(){$('recipe-results').innerHTML=currentMatches.length?currentMatches.map(m=>recipeCard(m.recipe,m)).join(''):empty('No matching meals yet','Try more pantry ingredients or a wider calorie range. Only recipes sharing ingredients are shown.');bindRecipes($('recipe-results'));}
function showRecipe(id){const r=recipes.find(r=>r.id===id),m=recipeNutrition(r,foods),inventory=new Map(pantry.map(p=>[p.food,p.grams]));
 $('recipe-dialog-content').innerHTML=`<img src="images/${r.image}.jpg" alt="Licensed serving suggestion"><p class="eyebrow">${r.minutes} MINUTES · ${r.servings} ${r.servings===1?'SERVING':'SERVINGS'}</p><h2>${esc(r.name)}</h2><p>${esc(r.description)}</p><p class="input-hint">Bundled food photograph; a serving suggestion, not a newly generated AI image.</p><div class="recipe-modal-macros">Per serving: ${fmt(m.kcal,0)} kcal · ${fmt(m.protein)} g protein · ${fmt(m.carbs)} g carbs · ${fmt(m.fat)} g fat</div><h3>Ingredients for the whole recipe</h3>${r.ingredients.map(p=>{const need=Math.max(0,p.grams-(inventory.get(p.food)||0));return `<div class="dialog-ingredient"><span>${esc(foods.get(p.food).name)}<small class="missing-badge">${need?` · Need ${gram(need)} g more`:' · Available'}</small></span><b>${gram(p.grams)} g</b></div>`;}).join('')}<h3>Make it, step by step</h3><ol>${r.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><p class="input-hint">Nutrition uses the listed ingredient weights and raw/cooked forms. Optional extras are not included. Check packaging and your own needs before relying on dietary labels.</p><div class="dialog-actions"><button class="primary" id="use-recipe">Log my version</button><button class="secondary" id="dialog-save-recipe">${isFavorite(id)?'Remove from saved':'Save recipe'}</button></div>`;
 $('use-recipe').onclick=()=>{$('recipe-dialog').close();useTemplate(r.id);showScreen('scanner');toast('Ingredients added as a starting point. Confirm your own quantities.');};
 $('dialog-save-recipe').onclick=guard(async()=>{const save=!isFavorite(id);await write('favorites',save?{id}:id,!save);await refreshKitchen();renderMatches();$('dialog-save-recipe').textContent=save?'Remove from saved':'Save recipe';toast(save?'Recipe saved.':'Recipe removed.');});
 $('recipe-dialog').showModal();
}
function useTemplate(id){const r=recipes.find(r=>r.id===id);if(!r)return;portions=r.ingredients.map(p=>({id:uid(),food:p.food,name:foods.get(p.food).name,grams:''}));$('meal-name').value=r.name;$('template').value=id;renderPortions();invalidate();}
function renderKitchen(){$('kitchen-stats').innerHTML=[['Pantry ingredients',pantry.length],['Saved recipes',favorites.length],['Meals remembered',meals.length]].map(([title,value])=>`<div class="kitchen-stat"><strong>${value}</strong><span>${title}</span></div>`).join('');const saved=recipes.filter(r=>isFavorite(r.id));$('favorite-recipes').innerHTML=saved.length?saved.map(r=>recipeCard(r)).join(''):empty('Keep your favorites close','Save a recipe from your pantry recommendations to see it here.');bindRecipes($('favorite-recipes'));
 $('meal-history').innerHTML=meals.length?meals.map(m=>`<article class="meal-log">${m.photo?`<img class="meal-thumb" src="${m.photo}" alt="Your saved meal photo">`:'<div class="meal-thumb">♧</div>'}<div><h3>${esc(m.name)}</h3><p>${esc(new Date(m.createdAt).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'}))} · ${m.portions.length} ingredients</p><div class="log-macros">${fmt(m.total.kcal,0)} kcal · ${fmt(m.total.protein)} g protein · ${fmt(m.total.carbs)} g carbs · ${fmt(m.total.fat)} g fat</div></div><button data-delete-meal="${m.id}" aria-label="Delete ${esc(m.name)}">Delete</button></article>`).join(''):empty('Remember a good meal','Calculate a meal’s nutrition and save it to start your journal.');$('meal-history').querySelectorAll('[data-delete-meal]').forEach(b=>b.onclick=guard(async()=>{await write('meals',b.dataset.deleteMeal,true);await refreshKitchen();toast('Meal removed from your journal.');}));$('kitchen-pantry').innerHTML=pantry.length?pantryMarkup(pantry,false):empty('Your pantry is empty','Add ingredients in “Cook from my pantry” to get started.');}
async function start(){
 try{
  const responses=await Promise.all([fetch('data/nutrition.json'),fetch('data/recipes.json')]);if(responses.some(r=>!r.ok))throw new Error('The food catalog could not load. Connect once and reload to set up offline use.');
  const [nutrition,recipeData]=await Promise.all(responses.map(r=>r.json()));foods=new Map(nutrition.ingredients.map(f=>[f.id,f]));recipes=recipeData;
  for(const r of recipes)recipeNutrition(r,foods);await openKitchen();await refreshKitchen();
  $('foods').innerHTML=[...foods.values()].sort((a,b)=>a.name.localeCompare(b.name)).map(f=>`<option value="${esc(f.name)}"></option>`).join('');$('template').innerHTML+=[...recipes].sort((a,b)=>a.name.localeCompare(b.name)).map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join('');
  document.querySelectorAll('[data-screen]').forEach(b=>b.onclick=()=>showScreen(b.dataset.screen));document.querySelectorAll('[data-go-pantry]').forEach(b=>b.onclick=()=>showScreen('pantry'));
  $('add-ingredient').onclick=()=>addPortion();$('template').onchange=()=>useTemplate($('template').value);
  $('camera-button').onclick=()=>$('camera-input').click();$('upload-button').onclick=()=>$('photo-input').click();
  for(const id of ['camera-input','photo-input'])$(id).onchange=guard(async()=>{await readPhoto($(id).files[0]);$(id).value='';});
  $('clear-photo').onclick=()=>{photo=null;renderPhoto();};
  $('calculate-button').onclick=()=>{try{result=calculateNutrition(portions,foods);$('calculation-error').hidden=true;renderNutrition();$('save-meal').disabled=false;$('breakdown').hidden=false;$('breakdown-content').innerHTML=result.breakdown.map(p=>`<div class="breakdown-row"><span>${esc(p.name)} · ${gram(p.grams)} g</span><b>${fmt(p.kcal,0)} kcal</b></div>`).join('');toast('Calculated locally from your confirmed quantities.');}catch(e){invalidate();$('calculation-error').textContent=e.message;$('calculation-error').hidden=false;}};
  $('save-meal').onclick=guard(async()=>{if(!result)throw new Error('Calculate nutrition before saving.');const name=$('meal-name').value.trim();if(!name)throw new Error('Give your meal a name before saving.');await write('meals',{id:uid(),name,createdAt:new Date().toISOString(),portions:result.breakdown.map(p=>({food:p.food,grams:p.grams})),total:result.total,photo});await refreshKitchen();toast('Meal saved privately in your kitchen.');});
  $('pantry-form').onsubmit=guard(async e=>{e.preventDefault();const f=resolveFood($('pantry-food').value);if(!f)throw new Error('Choose an ingredient from the list. Unknown foods are not assigned invented nutrition data.');const grams=parsePantryQuantity(f.id,$('pantry-quantity').value,$('pantry-unit').value);await write('pantry',{id:f.id,food:f.id,grams,unit:$('pantry-unit').value,quantity:Number($('pantry-quantity').value)},false,editPantry);resetPantryForm();await refreshKitchen();resetRecommendations();toast('Pantry saved on this device.');});$('cancel-edit').onclick=resetPantryForm;
  $('recommend-button').onclick=guard(async()=>{const bound=id=>$(id).value===''?null:Number($(id).value);currentMatches=rankRecipes(recipes,pantry,foods,{preference:$('diet').value,minKcal:bound('min-calories'),maxKcal:bound('max-calories')});renderMatches();if(!pantry.length)toast('Add pantry ingredients first.');});
  $('about-button').onclick=()=>$('about-dialog').showModal();document.querySelectorAll('.dialog-close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
  for(const dialog of document.querySelectorAll('dialog'))dialog.onclick=e=>{if(e.target===dialog){const rect=dialog.getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)dialog.close();}};
  addPortion();resetRecommendations();$('app-loading').hidden=true;showScreen(location.hash.slice(1));
  if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').then(()=>{navigator.serviceWorker.ready.then(()=>{$('offline-status').textContent=navigator.onLine?'Offline ready':'Offline mode';});}).catch(()=>{$('offline-status').textContent='Local & private';});
  window.addEventListener('online',()=>$('offline-status').textContent='Local & private');window.addEventListener('offline',()=>$('offline-status').textContent='Offline mode');
 }catch(e){$('app-loading').hidden=true;$('app-error').hidden=false;$('app-error').textContent=e.message;}
}
start();
